language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
script:
- ./gradlew check -i
- ./gradlew jacocoTestReport
before_deploy:
  - ./gradlew generateLicenseReport
  - ./gradlew javadoc
  - mkdir projectpage
  - cp -rv build/reports/* projectpage
  - cp -rv build/docs/* projectpage
  - cp -rv docs/* projectpage
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload -Ddeployment=true
    on:
      tags: true
      jdk: oraclejdk8
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: projectpage
    keep-history: false
    on:
      branch: master
      jdk: oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
