dist: focal
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_171b1c559d7b_key -iv $encrypted_171b1c559d7b_iv
  -in .ci/signingkey.asc.enc -out .ci/signingkey.asc -d
- gpg --batch --fast-import .ci/signingkey.asc
- gpg --version
install: true
script:
- mvn --settings .ci/mvn-settings.xml -DskipTests=false -Dgpg.skip=true clean install
deploy:
- provider: script
  script: export GPG_TTY=$(tty) && mvn --settings .ci/mvn-settings.xml -DskipTests=true
    -Drevision=${TRAVIS_TAG:1} clean deploy
  skip_cleanup: true
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: export GPG_TTY=$(tty) && mvn --settings .ci/mvn-settings.xml -DskipTests=true
    clean deploy
  on:
    branch: aligned-spring
after_success:
- echo "afterSuccess"
- bash <(curl -s https://codecov.io/bash)
- "./.ci/print_test_reports.sh"
after_failure:
- echo "afterFailure"
- "./.ci/print_test_reports.sh"
env:
  global:
  - LOG_LEVEL=WARN
  - secure: WgwCxkNgRN+tw8kwH8rJsBEiUE2mh3u96CbyN42jae7+YuiC8ki1EJitAQz4u7aCiWxfk6Pzf1v7DMFD0p2D15NKGOqT7fO9Lf3Hg+qakjke9BIBIHurwdfGe4AI3Uwbp4L4f++qcOgWyCCKZEel5P4x18Ya1L7/q+vg4bCV/3uFOYJuJ0l1s4oUNGeB8n3c1y3EOTd9k7wFPzAkMDatTsJ/kIS/+OOFlgM4RuAYMyLGTTr8K9723KrfcsBaPvPZb+pde/H2w1+eUPO0eiRoyBGjcqvAQqHzAv00zRbrPYGZGFydvEngbkOHrnBpt2dMyN/iCvLyaOqxtiIiWHdqM5WLf/HCqHQBDJMmICgIeaXGgcXCHnsczM83vymtTzrC46uzKBrflX59ihFMh9RegEcTmv7wi9PxDqET0BYE93lnb8vuOaAFGqd3i5F/QoSwVV2NhRRdcjjCRvMd8MBn9R+p07VhQF+aatYZ/ykU98OkOj9pJOCiB33UVLvvums2uDqUnA4l4V5R2D4uApNadDjUH9ZwsCByD1yR1lnZjsp7S1pAeT/UJLbXDyBNXNON+2RK4b4Saim3s4c2qLeR0vm/o8g+YeZUqHXVUkCvJ/iWy5wkh3hc7f1t2TUoAu4qXScc14+msdC/x4+NQtTnVOiF3EG5hvOfO3mHpgFq9qE=
  - secure: pbsG9TG6NwlXJbzn6y9Lqn1pt0uRO9u/pSI6StScWWUrbMn/Ty6RmNnTJxSEiBswSqrQb5yh9QCv+1VdwwDFWtsTmtb4ADtI63ekS/aTOnWBqXbRHERtPFsc9fA9NvjZJYgBeUeMWDxG2TqQCsu9Z9pGrU4AENb26QirVRDAIAdAOPX3DEki1jp7DF8pDUq7qLLQ7RtD9itOBGkF1X1aebD22eESq7z/OxNM8j0e0giEEjpJzOodRDM/MXc8eQ6L++RgHscMcFPGcjGQ9c5pausX5s1iGAbLNIc0/Zryzt5ZKjGLhrjlK5RUNYBvv7WVS5z5F9u3+TV54wyViETlODQk/SAvFbkuVkEPrIgE75cpBb0pgbHgXIxiTdk48tTzjUmtr2MTIDkQauuq+bE8m6u7ICABVR7tLCDyOH04i0K+re3KUOxvYht+BHTknCmVs8yK611ieFxvQXDh52bRTMtnx/TBNweM+6+NOIeGzdOzfPhZ41l5UaUEwiyMJHI4beANI/WYqMoqdgOMmrdmV2w0MHUtfL0G6W/dSCqSa/4GiCxyH6Hy/kK8DZsStVcZv819adLWLPVOD/60plP6Y4Y7+BJ7Lnfgx5bhOzAsVmMs31mEG2XJbJDeKQMswacH5xSf/LriL7tW6cd5rk9FDTnAgZHA8Ha/yqH1/XaMxEo=
